language: python
env:
  - DJANGO="Django>=1.11.0,<2.0.0"
  - DJANGO="Django>=2.0.0,<2.1.0"
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install $DJANGO
script:
  - ./test.sh
notifications:
  irc: "irc.freenode.org#mezzanine"
  on_success: change
  on_failure: change
